[package]
name = "hashbar"
version = "1.0.1"
edition = "2024"
license = "MIT"
documentation = "https://docs.rs/hashbar/latest/hashbar/"
repository = "https://github.com/tilosp/hashbar"
description = "Hash trait for hashing using the `digest` crate"

[dependencies]
digest = "0.10.7"
